# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI myapp

on:
  push:
    branches: [ test_branch_2 ]
  pull_request:
    branches: [ test_branch_1 ]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: MYDB
        ports:
          - 3306
        options:
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis
        ports:
          - 6379/tcp

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r src/myapp/requirements.txt; fi
        pip install -r src/myapp/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: verify MySQL connection from host
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        sudo service mysql start
        mysql -e "CREATE DATABASE MYDB"
        mysql -e "SHOW DATABASES"
    - name: Test with pytest
      run: |
        cd src/myapp
        export PYTHONPATH=/src:
        pytest tests

